FLRS/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url('^accounts/', include('django.contrib.auth.urls',namespace="auth")),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /paper/
    url(r'^paper$', views.paper_list, name='paper_list'),
    # ex: /paper/5/
    url(r'^paper/(?P<paper_recid>[0-9]+)/$', views.paper_detail, name='paper_detail'),
    url(r'^paper/(?P<paper_recid>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
    url(r'^paper/similar_(?P<paper_recid>[0-9]+)/$', views.show_similar_paper, name='show_similar_paper'),
    url(r'^search/$', views.search,name = 'search')
]

reviews/models.py
from __future__ import unicode_literals

from django.db import models
import numpy as np




class Author(models.Model):
    name = models.CharField(max_length=128)
    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Paper_cluster(models.Model):
    c_id = models.IntegerField()



class Paper(models.Model):
    name = models.CharField(max_length = 200)
    recid = models.IntegerField()
    abstract = models.CharField(max_length=2000)
    date = models.DateTimeField('date published',default="1900-01-01")
    author  = models.ManyToManyField(Author)
    cluster = models.ForeignKey(Paper_cluster, on_delete=models.CASCADE,default= 0)
    tfidf = models.CharField(max_length=5000,default = "")

    def vec_tfidf(self):
        return np.array(self.tfidf.split(','),dtype = np.float32)

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)

    def __unicode__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    paper = models.ForeignKey(Paper)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review
from django import forms

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

reviews/views.py
from django.shortcuts import get_object_or_404, render

from sklearn.neighbors import NearestNeighbors
from django.contrib.auth.decorators import login_required
from .models import Review, Paper,Paper_cluster,Author
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import ReviewForm
import datetime
import numpy as np
from collections import defaultdict



def find_similar_article(paper,num = 10):
    target = paper.vec_tfidf().reshape(1,-1)
    paper_list = paper.cluster.paper_set.exclude(recid = paper.recid)
    recid_list = np.array(map(lambda x:x.recid,paper_list))
    features = np.array(map(lambda x:x.vec_tfidf(),paper_list))

    NN_model = NearestNeighbors(n_neighbors=10, algorithm='brute', metric='cosine')
    NN_model.fit(features)

    try: num = int(num)
    except ValueError:
        num = 50

    score, similar_intem_index = NN_model.kneighbors(target, n_neighbors=num)
    recid_reults = recid_list[similar_intem_index[0]]
    qs = Paper.objects.filter(recid__in = recid_reults)

    qs_sorted = list()
    for id in recid_reults:
        qs_sorted.append(qs.get(recid=id))
    return qs_sorted, 1-score[0]


def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})

def check_form(request,subset = None):
    if "orderby" in request.POST:
        selected_value = request.POST["orderby"]
        if not subset:
            if selected_value == "Newest to Oldest":
                paper_list = Paper.objects.order_by('-date')
            elif selected_value == "Avg Rating: High to Low":
                paper_list = sorted(Paper.objects.all(),key = lambda x: 0 if np.isnan(x.average_rating())  else -x.average_rating())
            elif selected_value =='Num Rating: High to Low':
                paper_list = sorted(Paper.objects.all(),key = lambda x: -x.review_set.count())
            else:
                paper_list = Paper.objects.all()
        else:
            if selected_value == "Newest to Oldest":
                paper_list = subset.order_by('-date')
            elif selected_value == "Avg Rating: High to Low":
                paper_list = sorted(subset.all(),key = lambda x: 0 if np.isnan(x.average_rating())  else -x.average_rating())
            elif selected_value =='Num Rating: High to Low':
                paper_list = sorted(subset.all(),key = lambda x: -x.review_set.count())
            else:
                paper_list = subset.all()

        if 'number' in request.POST:
            show = request.POST['number']
            if show not in ["all",'Default'] :
                context = {'paper_list':paper_list[:int(show)], "rank": selected_value,'show':show}
            elif show == "Default":
                context = {'paper_list':paper_list[:50], "rank": selected_value,'show':"Default(50)"}
            else:
                context = {'paper_list':paper_list, "rank": selected_value,'show':show}

    else:
        if not subset:
            paper_list = Paper.objects.all()[:50]
            context = {'paper_list':paper_list}
        else:
            return {'paper_list':subset}
    return context



def paper_list(request):

    context = check_form(request)
    return render(request, 'reviews/paper_list.html', context)


def paper_detail(request, paper_recid):
    paper = get_object_or_404(Paper, recid=paper_recid)
    form = ReviewForm()
    return render(request, 'reviews/paper_detail.html', {'paper': paper, 'form': form})

@login_required
def add_review(request, paper_recid):
    paper = get_object_or_404(Paper, recid=paper_recid)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = request.user.username
        review = Review()
        review.paper = paper
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reviews:paper_detail', args=(paper.recid,)))

    return render(request, 'reviews/paper_detail.html', {'paper': paper, 'form': form})

@login_required
def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username':username}
    return render(request, 'reviews/user_review_list.html', context)

def user_recommendation_list(request):
    # get this user reviews
    user_reviews = Review.objects.filter(user_name=request.user.username).prefetch_related('paper')
    # from the reviews, get a set of wine IDs
    user_reviews_paper_ids = map(lambda x: x.paper.recid, user_reviews)
    # then get a wine list excluding the previous IDs
    if not user_reviews_paper_ids:
        paper_list = []
    else:
        ratings = np.array(map(lambda x:x.rating,user_reviews),dtype = float)
        ratings /= np.sum(ratings)
    sim = defaultdict(int)
    for i,j in enumerate(user_reviews):
        papers,score = find_similar_article(j.paper,num = 10)
        index = np.array(map(lambda x:x.recid,papers))
        score = ratings[i] * score
        for n in range(10):
            sim[index[n]] += score[n]
    out = np.array(sim.items(),dtype = object)
    out_sorted = np.array(sorted(out,key =lambda x:x[1])[::-1])

    context = check_form(request)
    if "show" in context.keys():
        try: show = int(context['show'])
        except ValueError:
            show = 50
    else:
        show = 10

    if out.shape[0] < show:
        recids = out_sorted[:,0]
    else:
        recids = out_sorted[:show,0]

    paper_list = []
    for i in recids:
        paper_list.append(Paper.objects.get(recid = i))

    return render(
        request,
        'reviews/user_recommendation_list.html',
        {'username': request.user.username,'paper_list': paper_list}
    )

def show_similar_paper(request,paper_recid):
    paper= get_object_or_404(Paper, recid=paper_recid)
    #paper_list = paper.cluster.paper_set.exclude(recid = paper.recid)
    paper_list = find_similar_article(paper,"50")[0]
    context = check_form(request,paper_list)
    context["paper_list"] = paper_list
    context['paper'] = paper
    if "show" in context.keys():
        context["paper_list"] =  find_similar_article(paper,context['show'])[0]

    return render(request, 'reviews/similar_paper.html', context)



def search(request):

    if "search_box" in request.GET:
        search_box = request.GET["search_box"]
        content = {}
        if 'search_by' in request.GET:
            if request.GET["search_by"]== "Text":
                content['paper_list'] = Paper.objects.filter(name__contains=search_box).all()
            elif request.GET['search_by'] == "Author":
                authors = Author.objects.filter(name__contains = search_box ).all()
                papers = map(lambda x:x.paper_set.all(),authors)
                paper_list = papers[0]
                for i in papers[1:]:
                    paper_list = paper_list|i
                content['paper_list'] = paper_list
            else:
                content['paper_list'] = Paper.objects.filter(name__contains=search_box).all()

            content['search_by'] = request.GET["search_by"]

        else:
            content['paper_list'] = Paper.objects.filter(name__contains=search_box).all()
        content['search_box'] = request.GET["search_box"]

    else:
        content = {'paper_list':Paper.objects.all()}

    #content = check_form(request,content)
    #content['paper_list'] = check_form(request)['paper_list']


    temp = check_form(request,content['paper_list'])

    if temp['paper_list']:
        if 'search_by' in content:
            content['paper_list'] = temp['paper_list']


        #     temp['search_by'] = content['search_by']
        # content = temp


    print(content.keys())

    return render(request, 'reviews/paper_list.html', content)

reviews/templates/reviews/paper_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ paper.name }}</h2>
    {% if paper.author.all  %}
            {% for author in paper.author.all %}
                <p style="float:left;color:#900;font-family:arial">{{ author.name }}</p>
                <div style="height:12px;width:20px;background-color:white;float:left;"></div>
            {% endfor %}

        {% endif %}
        <br>
        <span class = 'tt'> <p style="background-color: white;font-size: 14px;display: block;padding: 10px;border-radius: 5px;text-align: justify;">{{ paper.abstract }} </p></span>


<h5>{{ paper.review_set.count }} reviews ({{ paper.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if paper.review_set.all %}
<div class="row">
    {% for review in paper.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this paper yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' paper.recid %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
{% endblock %}

reviews/templates/reviews/paper_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% endblock %}





{% block content %}
    <div id="sbox" style="margin-top: 10px;
    text-align: center;">


  <form method="get" action="/reviews/search" style="display: block;
    margin-top: 0em;" class="nav-searchbar">
     <div class="nav-left">
      <img src= "/media/search1.png" style="width: 40px;height: 40px;float: right" />
    </div>


    <div class="wrapper" style="border: black">
  	<input name="search_box" class="inactive" type="text" id="qfield" style="
    width: 950px;
{#    border: solid 1px grey;#}
    height: 40px;
    font-size: 18px;
    color: black;
    " value="{{ search_box }}"
    >
      <select name = 'search_by' style="float: left;height: 35px; width: 130" >
            <option value="Default">Search By: {{ search_by }}</option>
            <option value="Author">Author</option>
            <option value="Text">Text</option>
        </select>
    </div>
  </form>



</div>

    <div class="msg" style="background-color: #EEF;
    padding: 10px;
    border-radius: 10px;
    margin-top: 2px;">
        Showing most recent papers:
    <form  method = "post" style="float: right">
        {% csrf_token %}
        <select name = 'number'>
            <option value="Default">Item: {{ show }}</option>
            <option value="10">Show 10</option>
            <option value="20">Show 20</option>
            <option value="all">Show all</option>
        </select>


        <select name="orderby">
            <option value="Defualt">Sort by: {{ rank }}</option>
            <option value="Newest to Oldest">Date: Newest to Oldest</option>
            <option value="Avg Rating: High to Low">Avg Rating: High to Low</option>
            <option value="Num Rating: High to Low">Num Rating: High to Low</option>
            <input type="submit" name = "Submit" value="Show" />
        </select>
      </form>
    </div>





{% if paper_list %}
<div class="row" style="margin-left: auto;
    margin-right: auto;
    background: white">
    {% for paper in paper_list %}
    <div class="apaper">
        <h4><a style="color:black;float:left" href="{% url 'reviews:paper_detail' paper.recid %}">
        {{ paper.name }}
        </a></h4>
        <h5> <a style="float: right;cursor: pointer;text-decoration: underline; display: inline-block;"  href="{% url 'reviews:show_similar_paper' paper.recid %}">
            Show similar Papers > </a> </h5>
        <br>
        {% if paper.author.all  %}
            {% for author in paper.author.all %}
                <p style="float:left;color:#900;font-family:arial">{{ author.name }}</p>
                <div style="height:12px;width:20px;background-color:white;float:left;"></div>
            {% endfor %}

        {% endif %}
        <br>
        <h5>{{ paper.date|date:"M/d/Y"}} </h5>
        <span class = 'tt'> <p style="background-color: #EFE;font-size: 14px;display: block;padding: 10px;border-radius: 5px;text-align: justify;">{{ paper.abstract }} </p></span>
        <h5>Reviews : {{ paper.review_set.count }} </h5>
        <h5>Average rating: {{ paper.average_rating | floatformat }} </h5>
        <br>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No papers are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/paper_list_origi.html
{% extends 'base.html' %}

{% block title %}
<h2>Paper list</h2>
{% endblock %}

{% block content %}
{% if paper_list %}
<div class="row">
    {% for paper in paper_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:paper_detail' paper.recid %}">
        {{ paper.name }}
        </a></h4>
        <h5>{{ paper.review_set.count }} reviews</h5>
        <h5>{{ paper.average_rating | floatformat }} average rating</h5>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No papers are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'reviews:paper_detail' review.paper.recid %}">{{ review.paper.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.paper.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }} at {{ review.pub_date|date:"M/d/Y" }}</h6>
        <p>comments: {{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/similar_paper.html
{% extends 'reviews/paper_list.html' %}

{% block title %}
{% endblock %}
{% block content %}
<div class="msg" style="background-color: #EEF;
    padding: 10px;
    border-radius: 10px;
    margin-top: 2px;
    color : darkred">Showing Similar papers for:
        <form  method = "post" style="float: right; color: black" >
        {% csrf_token %}
        <select name = 'number'>
            <option value="Default">Item: {{ show }}</option>
            <option value="10">Show 10</option>
            <option value="20">Show 20</option>
            <option value="all">Show all</option>
        </select>

        <select name="orderby">
          <option value="Defualt">Sort by: {{ rank }}</option>
            <option value="Newest to Oldest">Date: Newest to Oldest</option>
            <option value="Avg Rating: High to Low">Avg Rating: High to Low</option>
            <option value="Num Rating: High to Low">Num Rating: High to Low</option>
            <input type="submit" name = "Submit" value="Show" />
        </select>
      </form>
    <br>


<div style=" color : black">  {{ paper.name }} </div>
 </div>
 <br>


{% if paper_list %}
<div class="row"  style="margin-left: auto;
    margin-right: auto;
    ">
{% for paper_ in  paper_list|slice:":20" %}
    <div class="apaper">
        {% if paper_.recid != paper.recid  %}
        <h4><a style="color:black;float:left" href="{% url 'reviews:paper_detail' paper_.recid %}">
        {{ paper_.name }}
        </a></h4>
        <h5> <a style="float: right;cursor: pointer;text-decoration: underline; display: inline-block;"  href="{% url 'reviews:show_similar_paper' paper_.recid %}">
            Show similar Papers > </a> </h5>
        <br>
        {% if paper_.author.all  %}
            {% for author in paper_.author.all %}
                <p style="float:left;color:#900;font-family:arial">{{ author.name }}</p>
                <div style="height:12px;width:20px;background-color:white;float:left;"></div>
            {% endfor %}

        {% endif %}
        <br>
        <h5>{{ paper_.date|date:"M/d/Y"}} </h5>
        <span class = 'tt'> <p style="background-color: #EFE;font-size: 14px;display: block;padding: 10px;border-radius: 5px;text-align: justify;">{{ paper_.abstract }} </p></span>
        <h5>Reviews : {{ paper_.review_set.count }} </h5>
        <h5>Average rating: {{ paper_.average_rating | floatformat }} </h5>
        <br>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% else %}
<p>No similar paper detected</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/user_recommendation_list.html
{% extends 'reviews/paper_list.html' %}

{% block title %}
{% endblock %}
{% block content %}
<div class="msg" style="background-color: #EEF;
    padding: 10px;
    border-radius: 10px;
    margin-top: 2px;
    color : darkred">Showing paper suggestions for {{ username }}:
        <form  method = "post" style="float: right; color: black" >
        {% csrf_token %}
        <select name = 'number'>
            <option value="Default">Item: {{ show }}</option>
            <option value="10">Show 10</option>
            <option value="20">Show 20</option>
            <option value="all">Show all</option>
        </select>

        <select name="orderby">
          <option value="Defualt">Sort by: {{ rank }}</option>
            <option value="Newest to Oldest">Date: Newest to Oldest</option>
            <option value="Avg Rating: High to Low">Avg Rating: High to Low</option>
            <option value="Num Rating: High to Low">Num Rating: High to Low</option>
            <input type="submit" name = "Submit" value="Show" />
        </select>
      </form>
    <br>


<div style=" color : black">  {{ paper.name }} </div>
 </div>
 <br>

   {% if not paper_list %}
       <p>No review records found. Please review some paper First !</p>
    {%  else %}
       <div class="row" style="margin-left: auto;
    margin-right: auto;
    background: white">
    {% for paper in paper_list %}
    <div class="apaper">
        <h4><a style="color:black;float:left" href="{% url 'reviews:paper_detail' paper.recid %}">
        {{ paper.name }}
        </a></h4>
        <h5> <a style="float: right;cursor: pointer;text-decoration: underline; display: inline-block;"  href="{% url 'reviews:show_similar_paper' paper.recid %}">
            Show similar Papers > </a> </h5>
        <br>
        {% if paper.author.all  %}
            {% for author in paper.author.all %}
                <p style="float:left;color:#900;font-family:arial">{{ author.name }}</p>
                <div style="height:12px;width:20px;background-color:white;float:left;"></div>
            {% endfor %}

        {% endif %}
        <br>
        <h5>{{ paper.date|date:"M/d/Y"}} </h5>
        <span class = 'tt'> <p style="background-color: #EFE;font-size: 14px;display: block;padding: 10px;border-radius: 5px;text-align: justify;">{{ paper.abstract }} </p></span>
        <h5>Reviews : {{ paper.review_set.count }} </h5>
        <h5>Average rating: {{ paper.average_rating | floatformat }} </h5>
        <br>
    </div>
    {% endfor %}
</div>


    {% endif %}

{% endblock %}

reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Reviews by {{ username }}</h2>
{% endblock %}